In [1]:
#Question 1
import numpy as np
new_array=np.array([[1,2],[3,4],[5,5]])
new_list=new_array.tolist()
print(new_list)

[[1, 2], [3, 4], [5, 5]]


In [30]:
#Question 2
import numpy as np
a=np.random.randint(1,9,size=(3,3))
i=0
c=-1
sum=0
while i<len(a):
  sum+=a[i,i]
  sum+=a[c,i]
  i+=1
  c+=-1
print(a,'\n',"sum of the diagonal elements is:",sum)

[[4 3 5]
 [6 7 4]
 [2 5 7]] 
 sum of the diagonal elements is: 32


In [11]:
#Question 3
import numpy as np
x=np.random.randint(0,9)
a=np.array([[1,2],[3,5]])
i=0
result=list()
print('x=',x)
while i<len(a):
  b=0
  while b<len(a[i]):
    if a[i,b]>=x:
      result.append(a[i,b])
    b=b+1
  i+=1
print("the numbers higher than x are:",result)

x= 0
the numbers higher than x are: [1, 2, 3, 5]


In [5]:
#Question 4
import numpy as np
a=np.random.randint(0,9,size=(2,4))
b=np.random.randint(0,9,size=(2,4))
c=a+b
print("array 1:",a,'\n\n',"array 2:",b,'\n\n',"sum:",c)

array 1: [[4 2 0 0]
 [4 2 5 8]] 

 array 2: [[2 1 3 1]
 [4 7 1 8]] 

 sum: [[ 6  3  3  1]
 [ 8  9  6 16]]


In [ ]:
#Question 5import numpy as np
matrix=np.random.randint(0,9,size=(3,3))
print(matrix)
for i in matrix:
  print(np.mean(i))

